### ISSUE TITLE
Error while using more than one parametrized validator

### ISSUE THREAD

**Issue by Averor** [lezhnev74/pasvl#4]
"A pattern can have a single main validator name and any number of sub-validators."

But, in below example

        $pattern = [
            'test' => ':string :min(1) :max(255)'
        ];

        $test = [
            'test' => 'test value'
        ];

two validators are created, **string** and **min**, the last having argument of 

        1) :max(255

that means erroneous behavior.

Looking into 

    \PASVL\Pattern\Pattern::parse
method, and regexp used to match validator, mistake can be seen - no matching for closing parenthesis.

A little fix can be changing 
    
    $validator_arguments_pattern = "(\((?'arguments'.+,?)+\))?";
to

    $validator_arguments_pattern = "(\((?'arguments'[^)]+,?)+\))?";

Still, however, closing parenthesis used as part of argument (ex. for regexp validator) will cause some problems...

**Comment by lezhnev74** [comment]
Thanks for reporting! Will get my hands on it soon.

**Comment by lezhnev74** [comment]
Hey @Averor !
I spent a couple of hours thinking about this problem. I agree with your suggestion to improve regex with `[^)]+`. It definitely solves the problem of multiple sub-validators. 

As you correctly mentioned in the end, another test failed because it uses parenthesis within the regular expression:
`:string :regex(/so(me|ar)/,(((12))`. The only "quick" fix I came up with was to add possibility to escape "closing parenthesis" like this: `\)`. So the mentioned example became: `:string :regex(/so(me|ar\)/,(((12\))`

Now tests look green and probably I will merge this solution to master next week. However, the abovementioned solution is not "the best out there" and I hope to find a better one.

Let me know if you have other ideas of solving this issue.
